import 'package:todo_list/model/todo.dart';

final List<ToDo> dummyData = [
  ToDo(
    text: "Fai le pullizie",
    category: Category.leisure,
    priority: Priority.low,
    date: DateTime.now(),
  ),
  ToDo(
    text: "Porta lettore CD a riparare",
    category: Category.leisure,
    priority: Priority.medium,
    date: DateTime.now(),
  ),
  ToDo(
    text: "Compra il latte",
    category: Category.leisure,
    priority: Priority.hight,
    date: DateTime.now(),
  ),
  ToDo(
    text: "Chiama Mario",
    category: Category.leisure,
    priority: Priority.low,
    date: DateTime.now(),
  ),
  ToDo(
    text: "Organizza fotografie",
    category: Category.leisure,
    priority: Priority.medium,
    date: DateTime.now(),
  ),
  ToDo(
    text: "Compra acqua",
    category: Category.leisure,
    priority: Priority.hight,
    date: DateTime.now(),
  ),
  ToDo(
    text: "Vai dai parenti",
    category: Category.leisure,
    priority: Priority.medium,
    date: DateTime.now(),
  ),
  ToDo(
    text: "Vai a Roma",
    category: Category.work,
    priority: Priority.hight,
    date: DateTime.now(),
  ),
  ToDo(
    text: "Fai lavatrice",
    category: Category.leisure,
    priority: Priority.hight,
    date: DateTime.now(),
  ),
  ToDo(
    text: "Lava piatti",
    category: Category.leisure,
    priority: Priority.medium,
    date: DateTime.now(),
  ),
  ToDo(
    text: "Lava piatti",
    category: Category.leisure,
    priority: Priority.medium,
    date: DateTime.now(),
  ),
  ToDo(
    text: "Lava piatti",
    category: Category.leisure,
    priority: Priority.medium,
    date: DateTime.now(),
  ),
  ToDo(
    text: "Lava piatti",
    category: Category.leisure,
    priority: Priority.medium,
    date: DateTime.now(),
  ),
  ToDo(
    text: "Lava piatti",
    category: Category.leisure,
    priority: Priority.medium,
    date: DateTime.now(),
  ),
  ToDo(
    text: "Lava piatti",
    category: Category.leisure,
    priority: Priority.medium,
    date: DateTime.now(),
  ),
  ToDo(
    text: "Lava piatti",
    category: Category.leisure,
    priority: Priority.medium,
    date: DateTime.now(),
  ),
  ToDo(
    text: "Lava piatti",
    category: Category.leisure,
    priority: Priority.medium,
    date: DateTime.now(),
  ),
  ToDo(
    text: "Lava piatti",
    category: Category.leisure,
    priority: Priority.medium,
    date: DateTime.now(),
  ),
  ToDo(
    text: "Lava piatti",
    category: Category.leisure,
    priority: Priority.medium,
    date: DateTime.now(),
  ),
  ToDo(
    text: "Lava piatti",
    category: Category.leisure,
    priority: Priority.medium,
    date: DateTime.now(),
  ),
  ToDo(
    text: "Lava piatti",
    category: Category.leisure,
    priority: Priority.medium,
    date: DateTime.now(),
  ),
  ToDo(
    text: "Lava piatti",
    category: Category.leisure,
    priority: Priority.medium,
    date: DateTime.now(),
  ),
  ToDo(
    text: "Lava piatti",
    category: Category.leisure,
    priority: Priority.medium,
    date: DateTime.now(),
  ),
  ToDo(
    text: "Lava piatti",
    category: Category.leisure,
    priority: Priority.medium,
    date: DateTime.now(),
  ),
  ToDo(
    text: "Lava piatti",
    category: Category.leisure,
    priority: Priority.medium,
    date: DateTime.now(),
  ),
  ToDo(
    text: "Lava piatti",
    category: Category.leisure,
    priority: Priority.medium,
    date: DateTime.now(),
  ),
  ToDo(
    text: "Lava piatti",
    category: Category.leisure,
    priority: Priority.medium,
    date: DateTime.now(),
  ),
  ToDo(
    text: "Lava piatti",
    category: Category.leisure,
    priority: Priority.medium,
    date: DateTime.now(),
  ),
  ToDo(
    text: "Lava piatti",
    category: Category.leisure,
    priority: Priority.medium,
    date: DateTime.now(),
  ),
  ToDo(
    text: "Lava piatti",
    category: Category.leisure,
    priority: Priority.medium,
    date: DateTime.now(),
  ),
  ToDo(
    text: "Lava piatti",
    category: Category.leisure,
    priority: Priority.medium,
    date: DateTime.now(),
  ),
  ToDo(
    text: "Lava piatti",
    category: Category.leisure,
    priority: Priority.medium,
    date: DateTime.now(),
  ),
  ToDo(
    text: "Lava piatti",
    category: Category.leisure,
    priority: Priority.medium,
    date: DateTime.now(),
  ),
  ToDo(
    text: "Lava piatti",
    category: Category.leisure,
    priority: Priority.medium,
    date: DateTime.now(),
  ),
  ToDo(
    text: "Lava piatti",
    category: Category.leisure,
    priority: Priority.medium,
    date: DateTime.now(),
  ),
  ToDo(
    text: "Lava piatti",
    category: Category.leisure,
    priority: Priority.medium,
    date: DateTime.now(),
  ),
  ToDo(
    text: "Lava piatti",
    category: Category.leisure,
    priority: Priority.medium,
    date: DateTime.now(),
  ),
  ToDo(
    text: "Lava piatti",
    category: Category.leisure,
    priority: Priority.medium,
    date: DateTime.now(),
  ),
  ToDo(
    text: "Lava piatti",
    category: Category.leisure,
    priority: Priority.medium,
    date: DateTime.now(),
  ),
  ToDo(
    text: "Lava piatti",
    category: Category.leisure,
    priority: Priority.medium,
    date: DateTime.now(),
  ),
  ToDo(
    text: "Lava piatti",
    category: Category.leisure,
    priority: Priority.medium,
    date: DateTime.now(),
  ),
  ToDo(
    text: "Lava piatti",
    category: Category.leisure,
    priority: Priority.medium,
    date: DateTime.now(),
  ),
  ToDo(
    text: "Lava piatti",
    category: Category.leisure,
    priority: Priority.medium,
    date: DateTime.now(),
  ),
  ToDo(
    text: "Lava piatti",
    category: Category.leisure,
    priority: Priority.medium,
    date: DateTime.now(),
  ),
  ToDo(
    text: "Lava piatti",
    category: Category.leisure,
    priority: Priority.medium,
    date: DateTime.now(),
  ),
  ToDo(
    text: "Lava piatti",
    category: Category.leisure,
    priority: Priority.medium,
    date: DateTime.now(),
  ),
  ToDo(
    text: "Lava piatti",
    category: Category.leisure,
    priority: Priority.medium,
    date: DateTime.now(),
  ),
  ToDo(
    text: "Lava piatti",
    category: Category.leisure,
    priority: Priority.medium,
    date: DateTime.now(),
  ),
  ToDo(
    text: "Lava piatti",
    category: Category.leisure,
    priority: Priority.medium,
    date: DateTime.now(),
  ),
  ToDo(
    text: "Lava piatti",
    category: Category.leisure,
    priority: Priority.medium,
    date: DateTime.now(),
  ),
  ToDo(
    text: "Lava piatti",
    category: Category.leisure,
    priority: Priority.medium,
    date: DateTime.now(),
  ),
  ToDo(
    text: "Lava piatti",
    category: Category.leisure,
    priority: Priority.medium,
    date: DateTime.now(),
  ),
  ToDo(
    text: "Lava piatti",
    category: Category.leisure,
    priority: Priority.medium,
    date: DateTime.now(),
  ),
  ToDo(
    text: "Lava piatti",
    category: Category.leisure,
    priority: Priority.medium,
    date: DateTime.now(),
  ),
  ToDo(
    text: "Lava piatti",
    category: Category.leisure,
    priority: Priority.medium,
    date: DateTime.now(),
  ),
  ToDo(
    text: "Lava piatti",
    category: Category.leisure,
    priority: Priority.medium,
    date: DateTime.now(),
  ),
  ToDo(
    text: "Lava piatti",
    category: Category.leisure,
    priority: Priority.medium,
    date: DateTime.now(),
  ),
];
