name: todolistapp
version: '0.1.0'
summary: TODO List app.
description: TO DO List application.

base: core22
confinement: strict
grade: stable

architectures:
  - build-on: amd64
  # - build-on: arm64

apps:
  my-flutter-app:
    command: todolistapp
    extensions: [gnome]
    plugs: [network, network-bind]

parts:
  my-flutter-app:
    build-packages: [curl]
    source: .
    plugin: flutter
    flutter-target: lib/main.dart
